name: zap-stream-core
services:
  db:
    image: mariadb
    environment:
      - "MARIADB_ROOT_PASSWORD=root"
    ports:
      - "3368:3306"
    volumes:
      - "./dev-setup/db.sql:/docker-entrypoint-initdb.d/00-init.sql"
  relay:
    image: dockurr/strfry
    ports:
      - "7766:7777"
    volumes:
      - "relay:/app/strfry-db"
      - "./dev-setup/strfry.conf:/etc/strfry.conf"
  blossom:
    depends_on:
      - db
    image: voidic/route96:latest
    environment:
      - "RUST_LOG=info"
    ports:
      - "8881:8000"
    volumes:
      - "blossom:/app/data"
      - "./dev-setup/route96.yaml:/app/config.yaml"
  redis:
    image: redis
    ports:
      - "6399:6379"
  alby:
    image: ghcr.io/getalby/hub:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8882:8080"
    environment:
      - "RELAY=ws://host.docker.internal:7766"
      - "LND_ADDRESS=host.docker.internal:10001"
      - "LND_CERT_FILE=/root/.lnd/tls.cert"
      - "LND_MACAROON_FILE=/root/.lnd/data/chain/bitcoin/regtest/admin.macaroon"
      - "LN_BACKEND_TYPE=LND"
      - "NETWORK=regtest"
      - "WORK_DIR=/data"
    volumes:
      - "/home/kieran/.polar/networks/1/volumes/lnd/alice:/root/.lnd:ro"
      - "alby:/data"
volumes:
  db:
  blossom:
  relay:
  alby: