kind: pipeline
type: kubernetes
name: default
concurrency:
  limit: 1
metadata:
  namespace: git
volumes:
  - name: cache
    claim:
      name: storage2
  - name: temp
    temp: {}
steps:
  - name: Spawn Docker
    image: docker
    privileged: true
    detach: true
    volumes:
      - name: cache
        path: /cache
      - name: temp
        path: /dockerd
    commands:
      - dockerd --data-root /cache/dockerd --exec-root /dockerd --pidfile /dockerd/docker.pid -H unix:///dockerd/docker.sock
  - name: Login Docker
    image: docker
    volumes:
      - name: temp
        path: /dockerd
    environment:
      DOCKER_TOKEN:
        from_secret: docker_hub
      DOCKER_HOST: "unix:///dockerd/docker.sock"
    depends_on:
      - Spawn Docker
    commands:
      - docker login -u voidic -p $DOCKER_TOKEN
      - docker buildx create --platform linux/arm64,linux/amd64 --bootstrap --use
  - name: Build core AMD64
    image: docker
    volumes:
      - name: temp
        path: /dockerd
    environment:
      DOCKER_HOST: "unix:///dockerd/docker.sock"
    depends_on:
      - Login Docker
    commands:
      - docker buildx build --push --platform linux/amd64 -t voidic/zap-stream-core:latest -f ./crates/zap-stream/Dockerfile .
  - name: Build core ARM64
    image: docker
    volumes:
      - name: temp
        path: /dockerd
    environment:
      DOCKER_HOST: "unix:///dockerd/docker.sock"
    depends_on:
      - Login Docker
    commands:
      - docker buildx build --push --platform linux/arm64 -t voidic/zap-stream-core:latest -f ./crates/zap-stream/Dockerfile .
  - name: Build N94-Bridge
    image: docker
    volumes:
      - name: temp
        path: /dockerd
    environment:
      DOCKER_HOST: "unix:///dockerd/docker.sock"
    depends_on:
      - Login Docker
    commands:
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t voidic/n94-bridge:latest -f ./crates/n94-bridge/Dockerfile .
  - name: Kill docker
    image: docker
    volumes:
      - name: temp
        path: /dockerd
    depends_on:
      - Build N94-Bridge
      - Build core ARM64
      - Build core AMD64
    commands:
      - kill $(cat /dockerd/docker.pid)