kind: pipeline
type: kubernetes
name: default
concurrency:
  limit: 1
metadata:
  namespace: git
volumes:
  - name: cache
    claim:
      name: storage2
steps:
  - name: Spawn Docker
    image: docker
    privileged: true
    detach: true
    volumes:
      - name: cache
        path: /cache
    commands:
      - dockerd --data-root /cache/dockerd
  - name: Login Docker
    image: docker
    privileged: true
    environment:
      DOCKER_TOKEN:
        from_secret: docker_hub
    commands:
      - docker login -u voidic -p $DOCKER_TOKEN
      - docker buildx create --platform linux/arm64,linux/amd64 --bootstrap --use
  - name: Build core AMD64
    image: docker
    privileged: true
    commands:
      - docker buildx build --push --platform linux/amd64 -t voidic/zap-stream-core:latest -f ./crates/zap-stream/Dockerfile .
  - name: Build core ARM64
    image: docker
    privileged: true
    commands:
      - docker buildx build --push --platform linux/arm64 -t voidic/zap-stream-core:latest -f ./crates/zap-stream/Dockerfile .
  - name: Build N94-Bridge
    image: docker
    privileged: true
    commands:
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t voidic/n94-bridge:latest -f ./crates/n94-bridge/Dockerfile .
  - name: Kill docker
    image: docker
    privileged: true
    commands:
      - kill $(cat /var/run/docker.pid)