kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: docker
    privileged: true
    environment:
      TOKEN:
        from_secret: gitea
    commands:
      - dockerd &
      - docker login -u kieran -p $TOKEN git.v0l.io
      - docker buildx build --push -t git.v0l.io/kieran/zap-stream-core:latest .
      - kill $(cat /var/run/docker.pid)

