kind: pipeline
type: kubernetes
name: default
concurrency:
  limit: 1
metadata:
  namespace: git
volumes:
  - name: cache
    claim:
      name: storage2
steps:
  - name: build
    image: docker
    privileged: true
    volumes:
      - name: cache
        path: /cache
    environment:
      TOKEN:
        from_secret: gitea
      DOCKER_TOKEN:
        from_secret: docker_hub
    commands:
      - dockerd --data-root /cache/dockerd &
      - docker login -u voidic -p $DOCKER_TOKEN
      - docker buildx create --platform linux/arm64,linux/amd64 --bootstrap --use
      - docker buildx build --push --platform linux/amd64 -platform linux/arm64 -t voidic/zap-stream-core:latest -f ./crates/zap-stream/Dockerfile .
      - docker buildx build --push --platform linux/amd64 -t voidic/n94-bridge:latest -f ./crates/n94-bridge/Dockerfile .
      - kill $(cat /var/run/docker.pid)

